plugins:
  enable_devxy_login:
    default: false

  devxy_client_id:
    client: false
    default: ''
    validator: ValidateDevxyToggle

  devxy_secret:
    client: false
    default: ''
    secret: true
    validator: ValidateDevxyToggle
